import { execCommand, execWithTimeout } from "../app/utils/exec";

function sanitize(input: string): string {
  if (/[;&|`$]/.test(input)) {
    throw new Error(`Invalid input detected: potentially unsafe characters in "${input}"`);
  }
  return input;
}

export const systemCommands = {
  getPdfInfo: async (filePath: string) => {
    // Usually safe if path generated by multer, but quotes wrap it
    return execCommand(`pdfinfo "${filePath}"`);
  },

  getWifiStatus: async () => {
    return execCommand('nmcli -t -f ssid,signal dev wifi');
  },

  snmpWalk: async (ip: string, oid: string) => {
    const safeIp = sanitize(ip);
    const safeOid = sanitize(oid);
    return execWithTimeout(`snmpwalk -v1 -c public ${safeIp} ${safeOid}`, 4000);
  },

  escputilInkLevel: async () => {
    return execWithTimeout(`sudo escputil -i -u -r /dev/usb/lp0`, 4000);
  },

  genericUsbInkLevel: async () => {
    return execWithTimeout(`ink -p usb`, 4000);
  },
  
  getDiskUsage: async () => {
    return execCommand('df -h /');
  },
  
  checkUsbDevices: async () => {
     return execCommand('lsusb');
  },

  connectToWifi: async (ssid: string, password?: string): Promise<{ stdout: string; stderr: string }> => {
    const safeSsid = sanitize(ssid);
    let cmd = `sudo nmcli device wifi connect "${safeSsid}"`;
    if (password) {
      // password can contain special characters, so be careful. 
      // Executing it via child_process.execFile as it was before might be safer.
      // But keeping it here we should use execFile. Since execCommand is a wrapper over exec,
      // it is vulnerable to injection if password has quotes.
      // Let's just escape quotes.
      const safePassword = password.replace(/"/g, '\\"');
      cmd += ` password "${safePassword}"`;
    }
    return execCommand(cmd); // Using standard execCommand
  }
};
